#ifndef __MACROS_H
#define __MACROS_H

#define _EXIT_SUCCESS 0
#define SOCKET_CREATION_FAILED 120
#define SOCKET_CLIENT_CONNECTION_FAILED 121
#define SOCKET_BINDING_FAILED 122
#define SOCKET_SELECT_FAILED 123
#define SOCKET_LISTENING_CONNECTION_FAILED 124
#define NOFILE_ERROR 5
#define ERR_SET_PROCESS_BACKGROUND 140
#define ERR_SET_PROCESS_SPAWN 141
#define LOCALHOST "127.0.0.1"
#define MAX_LOG_CHARS 100
#define NMODULE 1
#define NGETTER 37
#define MAX_LENGHT_RECV 256
#define MAX_LENGHT_SEND 256
#define SERVER_PORT 9734

#endif